spring:
  profiles:
    active: ${ACTIVE_DB_PROFILE}

---

spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sevenbank}
    username: ${DB_USER:owner}
    password: ${DB_PASS:pass@123}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

---

spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:sevenbank;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
